# 巨量資料分析導論 Homework 4

# B036060012 政經大四 劉百耀

In [1]:
from sklearn.preprocessing import StandardScaler

In [2]:
data = [[0, 0], [0, 0], [1, 1], [1, 1]]
scaler = StandardScaler()
scaler.fit(data)
scaler.mean_

array([ 0.5,  0.5])

In [3]:
scaler.transform(data)

array([[-1., -1.],
       [-1., -1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [4]:
import numpy as np

In [5]:
class MyStandardScaler:
    
    def __init__(self):
        self.mean_ = None
        
    def fit(self, data):
        
        self.mean_ = np.mean(data, axis = 0)
        self.std_ = np.std(data, axis = 0)
        
    def transform(self, data):
        
        return (data - self.mean_) / self.std_
    
    def fit_transform(self, data):
        self.fit(data)
        return self.transform(data)

In [6]:
mystandardscaler = MyStandardScaler()
mystandardscaler.fit(data)
mystandardscaler.mean_

array([ 0.5,  0.5])

In [7]:
mystandardscaler.transform(data)

array([[-1., -1.],
       [-1., -1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [8]:
mystandanrdscaler_new = MyStandardScaler()
mystandanrdscaler_new.fit_transform(data)

array([[-1., -1.],
       [-1., -1.],
       [ 1.,  1.],
       [ 1.,  1.]])